import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet, Platform } from "react-native";

const { width } = Dimensions.get("window");
const isWeb = Platform.OS === "web";
const isMobileWeb = isWeb && width < 768;  // phone browser
const isDesktopWeb = isWeb && width >= 768; // laptop/desktop browser

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
        paddingHorizontal: isDesktopWeb ? 0 : 0,
        paddingTop: Platform.OS === 'ios' ? 60 : isDesktopWeb ? 0 : 40,
        paddingBottom: isDesktopWeb ? 0 : 40,
        maxWidth: isDesktopWeb ? '100%' : '100%',
        alignSelf: isDesktopWeb ? 'stretch' : 'stretch',
    },
    header: {
        alignItems: "center",
        marginBottom: isDesktopWeb ? 60 :0,
    },
    logoContainer: {
        width: isDesktopWeb ? 80 : 72,
        height: isDesktopWeb ? 80 : 72,
        borderRadius: isDesktopWeb ? 24 : 20,
        backgroundColor: "rgba(74, 222, 128, 0.15)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: isDesktopWeb ? 24 : 20,
        shadowColor: COLORS.primary,
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 8,
    },
    appName: {
        fontSize: isDesktopWeb ? 48 : 36,
        fontWeight: "800",
        fontFamily: "JetBrainsMono-Medium",
        color: COLORS.primary,
        letterSpacing: 1,
        marginBottom: isDesktopWeb ? 12 : 8,
    },
    tagline: {
        fontSize: isDesktopWeb ? 24 : 18,
        color: COLORS.white,
        fontWeight: "600",
        textAlign: "center",
        marginBottom: isDesktopWeb ? 8 : 4,
    },
    subtitle: {
        fontSize: isDesktopWeb ? 18 : 14,
        color: COLORS.grey,
        textAlign: "center",
        marginBottom: isDesktopWeb ? 12 : 8,
    },
    verifiedBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(74, 222, 128, 0.1)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(74, 222, 128, 0.3)",
    },
    verifiedText: {
        fontSize: 12,
        color: COLORS.primary,
        fontWeight: "600",
        marginLeft: 4,
    },
    illustrationContainer: {
        flex: isDesktopWeb ? 0 : 1,
        justifyContent: "center",
        alignItems: "center",
        marginVertical: isDesktopWeb ? 0 : 20,
        width: isDesktopWeb ? '100%' : 'auto',
    },
    illustration: {
        width: isDesktopWeb ? 400 : width * 0.8,
        height: isDesktopWeb ? 300 : width * 0.6,
        maxWidth: isDesktopWeb ? 500 : 400,
        maxHeight: isDesktopWeb ? 400 : 300,
        resizeMode: "contain",
    },
    contentSection: {
        flex: isDesktopWeb ? 0 : 1,
        justifyContent: isDesktopWeb ? 'flex-start' : 'flex-end',
        paddingBottom: Platform.OS === 'ios' ? 20 : isDesktopWeb ? 0 : 10,
        width: isDesktopWeb ? '100%' : 'auto',
    },
    welcomeText: {
        fontSize: isDesktopWeb ? 32 : 24,
        fontWeight: "700",
        color: COLORS.white,
        textAlign: isDesktopWeb ? 'left' : 'center',
        marginBottom: isDesktopWeb ? 12 : 8,
    },
    descriptionText: {
        fontSize: isDesktopWeb ? 18 : 16,
        color: COLORS.grey,
        textAlign: isDesktopWeb ? 'left' : 'center',
        marginBottom: isDesktopWeb ? 40 : 32,
        lineHeight: isDesktopWeb ? 28 : 24,
    },
    loginSection: {
        width: "100%",
        alignItems: isDesktopWeb ? 'flex-start' : 'center',
    },
    googleButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.white,
        paddingVertical: isDesktopWeb ? 20 : 18,
        paddingHorizontal: isDesktopWeb ? 32 : 24,
        borderRadius: isDesktopWeb ? 18 : 16,
        marginBottom: isDesktopWeb ? 24 : 20,
        width: isDesktopWeb ? 'auto' : "100%",
        maxWidth: isDesktopWeb ? 400 : 320,
        shadowColor: COLORS.background,
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.2,
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.1)",
    },
    googleIconContainer: {
        width: 24,
        height: 24,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    googleButtonText: {
        fontSize: isDesktopWeb ? 18 : 16,
        fontWeight: isDesktopWeb ? "700" : "800",
        color: COLORS.surface,
    },
    marketplaceInfo: {
        backgroundColor: "rgba(74, 222, 128, 0.05)",
        borderRadius: isDesktopWeb ? 16 : 12,
        padding: isDesktopWeb ? 24 : 16,
        marginBottom: isDesktopWeb ? 32 : 20,
        borderWidth: 1,
        borderColor: "rgba(74, 222, 128, 0.1)",
        width: isDesktopWeb ? '100%' : 'auto',
    },
    marketplaceTitle: {
        fontSize: isDesktopWeb ? 18 : 14,
        fontWeight: "600",
        color: COLORS.primary,
        textAlign: isDesktopWeb ? 'left' : 'center',
        marginBottom: isDesktopWeb ? 12 : 8,
    },
    marketplaceDescription: {
        fontSize: isDesktopWeb ? 14 : 12,
        color: COLORS.grey,
        textAlign: isDesktopWeb ? 'left' : 'center',
        lineHeight: isDesktopWeb ? 22 : 18,
    },
    termsText: {
        textAlign: isDesktopWeb ? 'left' : 'center',
        fontSize: isDesktopWeb ? 14 : 12,
        color: COLORS.grey,
        maxWidth: isDesktopWeb ? 400 : 280,
        lineHeight: isDesktopWeb ? 22 : 18,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: isDesktopWeb ? 18 : 16,
    },
    loadingText: {
        color: COLORS.white,
        fontSize: isDesktopWeb ? 18 : 16,
        fontWeight: "600",
    },
    errorContainer: {
        backgroundColor: "rgba(239, 68, 68, 0.1)",
        borderRadius: isDesktopWeb ? 16 : 12,
        padding: isDesktopWeb ? 20 : 16,
        marginBottom: isDesktopWeb ? 24 : 20,
        borderWidth: 1,
        borderColor: "rgba(239, 68, 68, 0.2)",
        width: isDesktopWeb ? '100%' : 'auto',
    },
    errorText: {
        color: COLORS.error,
        fontSize: isDesktopWeb ? 16 : 14,
        textAlign: isDesktopWeb ? 'left' : 'center',
        fontWeight: "500",
    },
    // Legacy styles for backward compatibility
    splitContainer: {
        flex: 1,
        flexDirection: Platform.OS === 'web' ? 'row' : 'column',
        width: '100%',
        height: '100%',
        backgroundColor: COLORS.background,
    },
    leftPane: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.background,
        padding: 0,
        minHeight: 0,
        minWidth: 0,
    },
    rightPane: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.background,
        minHeight: 0,
        minWidth: 0,
        padding: 0,
    },
    brandSection: {
        alignItems: "center",
        width: '100%',
        maxWidth: 420,
        padding: 24,
        boxSizing: 'border-box',
    },
}); 
export default styles;