import {Platform, StyleSheet} from "react-native";
import {COLORS} from "@/app/(automation)/colors";

export const styles = StyleSheet.create({
    header: {
        paddingTop: 20,
        paddingHorizontal: 20,
        paddingBottom: 10,
        backgroundColor: COLORS.background,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: COLORS.surface,
    },
    title: {
        fontSize: 22,
        fontWeight: '600',
        color: COLORS.white,
    },
    stopLiveButton: {
        borderRadius: 8,
        overflow: 'hidden',
        minWidth: 100,
    },
    stopLiveTouchable: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stopLive: {
        color: COLORS.white,
        fontWeight: '600',
        fontSize: 14,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: 20,
        paddingHorizontal: 8,
        backgroundColor: COLORS.background,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '500',
        color: COLORS.white,
        marginTop: 32,
        marginBottom: 14,
    },
    sectionHeader: {
        fontSize: 30,
        fontWeight: '500',
        color: COLORS.instagram.red,
        marginTop: 32,
        marginBottom: 14,
    },
    label: {
        color: COLORS.grey,
        fontSize: 14,
        marginBottom: 8,
        marginTop: 18,
    },
    input: {
        backgroundColor: COLORS.surface,
        color: COLORS.white,
        padding: 12,
        borderRadius: 8,
        marginBottom: 18,
        borderWidth: 1,
        borderColor: COLORS.surfaceLight,
        fontSize: 16,
        width: '100%',
    },
    inputHint: {
        color: COLORS.grey,
        fontSize: 12,
        marginBottom: 12,
        marginLeft: 4,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        gap: 8,
    },
    statusDot: {
        color: COLORS.grey,
        fontSize: 18,
        marginHorizontal: 2,
    },
    statusOffline: {
        color: COLORS.grey,
        fontSize: 15,
        marginHorizontal: 6,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingText: {
        color: COLORS.white,
        fontSize: 16,
        marginTop: 12,
        fontWeight: '500',
    },
    goLiveButton: {
        borderRadius: 16,
        marginTop: 10,
        marginBottom: 30,
        overflow: 'hidden',
        alignSelf: 'center',
        width: '90%',
    },
    goLiveTouchable: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
    },
    goLiveText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 18,
    },
    multilineInput: {
        minHeight: 70,
        textAlignVertical: 'top',
    },
    disabledButton: {
        opacity: 0.5,
    },
    disabledText: {
        color: COLORS.grey,
    },
    warningContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(253, 29, 29, 0.1)',
        padding: 12,
        marginHorizontal: 16,
        marginTop: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: COLORS.instagram.orange,
    },
    warningText: {
        color: COLORS.white,
        marginLeft: 8,
        fontSize: 14,
        flex: 1,
    },
    mainContainer: {
        flex: 1,
        flexDirection: Platform.OS === 'web' ? 'row' : 'column',
        width: '100%',
        alignItems: 'stretch',
        justifyContent: 'center',
        minHeight: 0,
        height: '100%',
    },
    leftColumn: {
        width: '50%',
        height: '100%',
        backgroundColor: COLORS.background,
        display: 'flex',
        boxSizing: 'border-box',
        padding: 0,
        overflow: Platform.OS === 'web' ? 'scroll' : 'visible',
    },
    leftColumnContent: {
        width: '80%',
        maxWidth: 400,
        paddingBottom: 40,
        flexGrow: 1,
        flexDirection: 'column',
        alignSelf: 'center',
        height: '100%',
        display: 'flex',
    },
    verticalDivider: {
        width: 1,
        backgroundColor: COLORS.surfaceLight,
        alignSelf: 'stretch',
        display: Platform.OS === 'web' ? 'flex' : 'none',
    },
    rightColumn: {
        width: '50%',
        height: '100%',
        backgroundColor: COLORS.background,
        boxSizing: 'border-box',
        padding: 32,
        overflow: Platform.OS === 'web' ? 'scroll' : 'visible',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1001,
    },
    modalContainer: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        padding: 24,
        margin: 20,
        minWidth: 280,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 16,
        elevation: 8,
    },
    modalTitle: {
        color: COLORS.white,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 12,
    },
    modalMessage: {
        color: COLORS.grey,
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    modalButton: {
        borderRadius: 12,
        overflow: 'hidden',
    },
    modalButtonTouchable: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        color: COLORS.white,
        fontSize: 16,
        fontWeight: '600',
    },
});
